"""baseline initial schema

Baseline migration for QuantBlade: creates every table defined in
``app/models/``. Generated with ``alembic revision --autogenerate`` and then
reviewed; the table set was verified against the ORM metadata.

Tables (11):
  stocks, stock_daily, factor_values, stock_fundamentals, stock_rankings,
  trading_accounts, trading_positions, trading_logs, alert_rules, alert_logs,
  ai_picks

Existing databases: this baseline targets *fresh* databases. A database already
created by ``Base.metadata.create_all`` (e.g. the in-use stock_picker.db) should
be stamped rather than upgraded, so Alembic records the baseline as applied:

    .venv/bin/python -m alembic stamp head

``upgrade()`` is additionally idempotent: it skips tables that already exist, so
running it against a partially-populated database will not fail.

Revision ID: 0001
Revises:
Create Date: 2026-09-29 22:11:55.186546

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _existing_tables() -> set:
    """Names of tables already present in the target database."""
    return set(sa.inspect(op.get_bind()).get_table_names())


class _SkipIndexBatch:
    """Batch-operation proxy that ignores index creation.

    Used only in ``upgrade()`` for tables that already exist, where the baseline
    must not try to re-create the indexes that ``create_all`` already made.
    Real batch operations that are not index-related pass through unchanged.
    """

    _SKIPPED = frozenset({"create_index", "create_unique_constraint"})

    @staticmethod
    def f(name: str) -> str:
        """Mirror ``BatchOperations.f()`` (naming convention for indexes)."""
        return name

    def __getattr__(self, item):
        if item in self._SKIPPED:
            return lambda *args, **kwargs: None
        raise AttributeError(item)


def upgrade() -> None:
    existing = _existing_tables()

    # --- idempotency guards -------------------------------------------------
    # A database created earlier by Base.metadata.create_all already contains
    # these tables and their indexes. Skip anything already present so an
    # accidental `upgrade head` against a live schema cannot fail (or lose data).
    _create_table = op.create_table

    def create_table(name, *args, **kwargs):
        """Create a table unless it already exists."""
        if name in existing:
            return None
        return _create_table(name, *args, **kwargs)

    op.create_table = create_table

    from contextlib import contextmanager

    _batch_alter_table = op.batch_alter_table
    _skip = _SkipIndexBatch()

    @contextmanager
    def batch_alter_table(table_name, *args, **kwargs):
        """Yield a no-op proxy for pre-existing tables, else the real batch op."""
        if table_name in existing:
            yield _skip
        else:
            with _batch_alter_table(table_name, *args, **kwargs) as batch_op:
                yield batch_op

    op.batch_alter_table = batch_alter_table
    # --- end guards ---------------------------------------------------------

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_picks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pick_date', sa.Date(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('price_at_pick', sa.Float(), nullable=True),
    sa.Column('next_day_open', sa.Float(), nullable=True),
    sa.Column('next_day_close', sa.Float(), nullable=True),
    sa.Column('next_day_change_pct', sa.Float(), nullable=True),
    sa.Column('backtest_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('ai_picks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_picks_pick_date'), ['pick_date'], unique=False)

    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('params', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('notify_wechat', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factor_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('factor_name', sa.String(length=50), nullable=False),
    sa.Column('factor_type', sa.Enum('TECHNICAL', 'FUNDAMENTAL', 'SENTIMENT', name='factortype'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('factor_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_factor_values_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_factor_values_factor_name'), ['factor_name'], unique=False)

    op.create_table('stock_rankings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('rank_date', sa.Date(), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.Column('industry_rank', sa.Integer(), nullable=True),
    sa.Column('tech_score', sa.Float(), nullable=False),
    sa.Column('fund_score', sa.Float(), nullable=False),
    sa.Column('sent_score', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('stock_rankings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_rankings_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_rankings_rank_date'), ['rank_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_rankings_strategy'), ['strategy'], unique=False)

    op.create_table('stocks',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('list_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('trading_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('initial_capital', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('prev_close_value', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trading_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('trading_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trading_logs_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trading_logs_code'), ['code'], unique=False)

    op.create_table('trading_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('avg_cost', sa.Float(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_since_open', sa.Float(), nullable=False),
    sa.Column('atr_at_buy', sa.Float(), nullable=False),
    sa.Column('stop_loss_price', sa.Float(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('trading_positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trading_positions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trading_positions_code'), ['code'], unique=False)

    op.create_table('alert_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['code'], ['stocks.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('stock_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_daily_code'), ['code'], unique=False)

    op.create_table('stock_fundamentals',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('pe_ttm', sa.Float(), nullable=True),
    sa.Column('pb', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('revenue_growth', sa.Float(), nullable=True),
    sa.Column('profit_growth', sa.Float(), nullable=True),
    sa.Column('debt_ratio', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['code'], ['stocks.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_fundamentals')
    with op.batch_alter_table('stock_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_daily_code'))

    op.drop_table('stock_daily')
    op.drop_table('alert_logs')
    with op.batch_alter_table('trading_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trading_positions_code'))
        batch_op.drop_index(batch_op.f('ix_trading_positions_account_id'))

    op.drop_table('trading_positions')
    with op.batch_alter_table('trading_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trading_logs_code'))
        batch_op.drop_index(batch_op.f('ix_trading_logs_account_id'))

    op.drop_table('trading_logs')
    op.drop_table('trading_accounts')
    op.drop_table('stocks')
    with op.batch_alter_table('stock_rankings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_rankings_strategy'))
        batch_op.drop_index(batch_op.f('ix_stock_rankings_rank_date'))
        batch_op.drop_index(batch_op.f('ix_stock_rankings_code'))

    op.drop_table('stock_rankings')
    with op.batch_alter_table('factor_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_factor_values_factor_name'))
        batch_op.drop_index(batch_op.f('ix_factor_values_code'))

    op.drop_table('factor_values')
    op.drop_table('alert_rules')
    with op.batch_alter_table('ai_picks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_picks_pick_date'))

    op.drop_table('ai_picks')
    # ### end Alembic commands ###
